---
output: github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  fig.path = "man/figures/README-"
)
```


# `tdf`

Installation 
---

To install the package, use
```{r, eval = FALSE}
devtools::install_github("alastairrushworth/tdf")
```

Usage
---

Load the package and check out the help file

```{r}
library(tdf)
?winners
```

Quick summary of the columns and their contents

```r
tibble::glimpse(winners)

Observations: 106
Variables: 19
$ edition       <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…
$ start_date    <date> 1903-07-01, 1904-07-02, 1905-07-09, 1906-07-04, 1907-07-08, 1…
$ winner_name   <chr> "Maurice Garin", "Henri Cornet", "Louis Trousselier", "René Po…
$ winner_team   <chr> "La Française", "Conte", "Peugeot–Wolber", "Peugeot–Wolber", "…
$ distance      <dbl> 2428, 2428, 2994, 4637, 4488, 4497, 4498, 4734, 5343, 5289, 52…
$ time_overall  <dbl> 94.55389, 96.09861, NA, NA, NA, NA, NA, NA, NA, NA, 197.90000,…
$ time_margin   <dbl> 2.98916667, 2.27055556, NA, NA, NA, NA, NA, NA, NA, NA, 0.1355…
$ stage_wins    <dbl> 3, 1, 5, 5, 2, 5, 6, 4, 2, 3, 1, 1, 1, 4, 2, 0, 3, 4, 4, 2, 3,…
$ stages_led    <dbl> 6, 3, 10, 12, 5, 13, 13, 3, 13, 13, 8, 15, 2, 14, 14, 3, 6, 15…
$ height        <dbl> 1.62, NA, NA, NA, NA, NA, 1.78, NA, NA, NA, NA, NA, NA, NA, NA…
$ weight        <dbl> 60, NA, NA, NA, NA, NA, 88, NA, NA, NA, NA, NA, NA, NA, NA, NA…
$ age           <int> 32, 19, 24, 27, 24, 25, 22, 22, 26, 23, 23, 24, 33, 30, 33, 36…
$ born          <date> 1871-03-03, 1884-08-04, 1881-06-29, 1879-06-05, 1882-10-18, 1…
$ died          <date> 1957-02-19, 1941-03-18, 1939-04-24, 1907-01-25, 1917-12-20, 1…
$ full_name     <chr> NA, NA, NA, NA, "Lucien Georges Mazan", "Lucien Georges Mazan"…
$ nickname      <chr> "The Little Chimney-sweep", "Le rigolo (The joker)", "Levaloy …
$ birth_town    <chr> "Arvier", "Desvres", "Paris", "Moret-sur-Loing", "Plessé", "Pl…
$ birth_country <chr> "Italy", "France", "France", "France", "France", "France", "Fr…
$ nationality   <chr> " France", " France", " France", " France", " France", " Franc…

```


Comments? Suggestions? Issues?
---  

Any feedback is welcome! Feel free to write a github issue or send me a message on [twitter](https://twitter.com/rushworth_a).
